import type { Trip, TripAction } from "./types";

function maps(query: string) {
  return `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(query)}`;
}

export const SALVADOR_TRIP: Trip = {
  slug: "salvador",
  title: "Salvador",
  subtitle: "Praia calma, Pelourinho e Massarandupió",
  dates: "31 out — 05 nov 2026 · 5 noites",
  days: [
    {
      key: "2026-10-31",
      label: "31/out",
      weekday: "Sexta",
      focus: "Chegada · Stella Maris",
    },
    {
      key: "2026-11-01",
      label: "01/nov",
      weekday: "Sábado",
      focus: "Pelourinho · com carro",
    },
    {
      key: "2026-11-02",
      label: "02/nov",
      weekday: "Domingo",
      focus: "Massarandupió · devolver carro",
    },
    {
      key: "2026-11-03",
      label: "03/nov",
      weekday: "Segunda · Finados",
      focus: "Descanso · praia local",
    },
    {
      key: "2026-11-04",
      label: "04/nov",
      weekday: "Terça",
      focus: "Barra · Farol",
    },
    {
      key: "2026-11-05",
      label: "05/nov",
      weekday: "Quarta",
      focus: "Check-out · voo",
    },
    {
      key: "antes",
      label: "Antes",
      weekday: "Preparação",
      focus: "Confirmar e empacotar",
    },
  ],
};

const actions: Omit<TripAction, "done" | "custom" | "tripSlug">[] = [
  {
    dayKey: "antes",
    dayLabel: "Antes",
    sort: 10,
    title: "Confirmar local de retirada e devolução do carro",
    notes: "Retirada 01/nov 06h · devolução 02/nov 21h. Documentos e cartão para caução.",
    category: "checklist",
  },
  {
    dayKey: "antes",
    dayLabel: "Antes",
    sort: 20,
    title: "Confirmar com a hospedagem: vaga, cozinha e check-in",
    notes: "Chegada prevista ~13h35 · check-in após 14h.",
    category: "checklist",
  },
  {
    dayKey: "antes",
    dayLabel: "Antes",
    sort: 30,
    title: "Checar horários no Instagram dos restaurantes veganos",
    notes: "@bvegan.ssa · @rangovegan · @midispachevegan · @nana.veg",
    category: "checklist",
    placeName: "Instagram vegano SSA",
    placeUrl: "https://www.instagram.com/bvegan.ssa/",
  },
  {
    dayKey: "antes",
    dayLabel: "Antes",
    sort: 40,
    title: "Consultar tábua de marés de Stella Maris",
    notes: "Piscinas naturais na maré baixa.",
    category: "checklist",
    placeName: "Tábua de marés — Salvador",
    placeUrl: "https://www.tabuademares.com/br/bahia/salvador",
  },
  {
    dayKey: "antes",
    dayLabel: "Antes",
    sort: 50,
    title: "Protetor FPS 50+, chapéu, tênis, CNH e apps de corrida/GPS",
    category: "checklist",
  },
  {
    dayKey: "2026-10-31",
    dayLabel: "31/out",
    sort: 10,
    time: "11:55",
    title: "Voo de ida",
    notes: "Direto · cerca de 1h40 · chegada 13h35.",
    category: "logistica",
    placeName: "Aeroporto Internacional de Salvador (SSA)",
    placeUrl: maps("Aeroporto Internacional de Salvador Deputado Luís Eduardo Magalhães SSA"),
  },
  {
    dayKey: "2026-10-31",
    dayLabel: "31/out",
    sort: 20,
    time: "13:35",
    title: "Desembarque e corrida até a hospedagem",
    notes: "~15–25 min. Check-in após 14h.",
    category: "logistica",
    placeName: "Stella Maris, Salvador",
    placeUrl: maps("Stella Maris Salvador BA"),
  },
  {
    dayKey: "2026-10-31",
    dayLabel: "31/out",
    sort: 30,
    time: "15:00",
    title: "Praia de Stella Maris",
    notes: "Sem carro hoje. Farol da Barra fica longe (~40 min).",
    category: "passeio",
    placeName: "Praia de Stella Maris",
    placeUrl: maps("Praia de Stella Maris Salvador"),
  },
  {
    dayKey: "2026-10-31",
    dayLabel: "31/out",
    sort: 40,
    time: "19:00",
    title: "Jantar na hospedagem ou delivery vegano",
    notes: "iFood B-Vegan (sex 15h–21h30) ou mercado.",
    category: "comida",
    placeName: "B-Vegan",
    placeUrl: maps("B-Vegan Salvador Barra"),
  },
  {
    dayKey: "2026-10-31",
    dayLabel: "31/out",
    sort: 50,
    time: "21:00",
    title: "Organizar marmita leve para o sábado",
    notes: "Dia longo com carro.",
    category: "checklist",
  },
  {
    dayKey: "2026-11-01",
    dayLabel: "01/nov",
    sort: 10,
    time: "05:00",
    title: "Acordar cedo para retirar o carro",
    notes: "Sair ~05:15. Retirada às 06:00.",
    category: "checklist",
  },
  {
    dayKey: "2026-11-01",
    dayLabel: "01/nov",
    sort: 20,
    time: "05:15",
    title: "Corrida até a locadora",
    notes: "Confirmar endereço na reserva. Não subir ao Pelourinho com o carro.",
    category: "logistica",
    placeName: "Foco Rent a Car Salvador",
    placeUrl: maps("Foco Rent a Car Salvador aeroporto"),
  },
  {
    dayKey: "2026-11-01",
    dayLabel: "01/nov",
    sort: 30,
    time: "07:30",
    title: "Chegada ao centro — estacionar e ir a pé",
    notes: "Shopping Barra ou Cidade Baixa.",
    category: "logistica",
    placeName: "Pelourinho, Salvador",
    placeUrl: maps("Largo do Pelourinho Salvador"),
  },
  {
    dayKey: "2026-11-01",
    dayLabel: "01/nov",
    sort: 40,
    time: "09:30",
    title: "Largo do Pelourinho, São Francisco e Elevador Lacerda",
    notes: "Sábado = centro no auge. ~4h a pé.",
    category: "passeio",
    placeName: "Igreja de São Francisco — Pelourinho",
    placeUrl: maps("Igreja e Convento de São Francisco Pelourinho Salvador"),
  },
  {
    dayKey: "2026-11-01",
    dayLabel: "01/nov",
    sort: 45,
    title: "Elevador Lacerda",
    category: "passeio",
    placeName: "Elevador Lacerda",
    placeUrl: maps("Elevador Lacerda Salvador"),
  },
  {
    dayKey: "2026-11-01",
    dayLabel: "01/nov",
    sort: 50,
    time: "13:00",
    title: "Almoço no Rango Vegan",
    notes: "Sáb 12h–16h.",
    category: "comida",
    placeName: "Rango Vegan",
    placeUrl: maps("Rango Vegan Pelourinho Salvador"),
  },
  {
    dayKey: "2026-11-01",
    dayLabel: "01/nov",
    sort: 60,
    time: "15:00",
    title: "MAM ou descanso",
    category: "passeio",
    placeName: "MAM Salvador",
    placeUrl: maps("Museu de Arte Moderna da Bahia MAM Salvador"),
  },
  {
    dayKey: "2026-11-01",
    dayLabel: "01/nov",
    sort: 70,
    time: "17:00",
    title: "Rio Vermelho — Nana Veg",
    notes: "Sábado até 18h.",
    category: "comida",
    placeName: "Nana Veg",
    placeUrl: maps("Nana Veg Rio Vermelho Salvador"),
  },
  {
    dayKey: "2026-11-01",
    dayLabel: "01/nov",
    sort: 80,
    time: "20:00",
    title: "Jantar no Rango Vegan",
    notes: "Sáb 17h–22h. Levar take-away para marmita de domingo.",
    category: "comida",
    placeName: "Rango Vegan",
    placeUrl: maps("Rango Vegan Pelourinho Salvador"),
  },
  {
    dayKey: "2026-11-01",
    dayLabel: "01/nov",
    sort: 90,
    time: "22:00",
    title: "Retorno de carro para Stella Maris",
    category: "logistica",
    placeName: "Stella Maris, Salvador",
    placeUrl: maps("Stella Maris Salvador BA"),
  },
  {
    dayKey: "2026-11-01",
    dayLabel: "01/nov",
    sort: 100,
    time: "noite",
    title: "Preparar marmita e água para Massarandupió",
    notes: "Vila é peixe/moqueca. Take-away B-Vegan/Rango ou cozinha.",
    category: "checklist",
  },
  {
    dayKey: "2026-11-02",
    dayLabel: "02/nov",
    sort: 10,
    time: "06:30",
    title: "Saída para Massarandupió",
    notes: "Av. Paralela / BA-099 (Linha Verde) · ~1h35–2h · ~100 km. Sem ferry. Estrada de terra nos últimos 8–10 km.",
    category: "logistica",
    placeName: "Praia de Massarandupió",
    placeUrl: maps("Praia de Massarandupió Bahia"),
  },
  {
    dayKey: "2026-11-02",
    dayLabel: "02/nov",
    sort: 20,
    time: "09:00",
    title: "Praia e coqueirais em Massarandupió",
    notes: "Estacionamento gratuito. Corrida de app não é confiável na volta.",
    category: "passeio",
    placeName: "Praia de Massarandupió",
    placeUrl: maps("Praia de Massarandupió Bahia"),
  },
  {
    dayKey: "2026-11-02",
    dayLabel: "02/nov",
    sort: 30,
    time: "12:00",
    title: "Almoço: marmita na praia",
    category: "comida",
  },
  {
    dayKey: "2026-11-02",
    dayLabel: "02/nov",
    sort: 40,
    time: "15:30",
    title: "Volta · troca de roupa em Stella Maris",
    category: "logistica",
    placeName: "Stella Maris, Salvador",
    placeUrl: maps("Stella Maris Salvador BA"),
  },
  {
    dayKey: "2026-11-02",
    dayLabel: "02/nov",
    sort: 50,
    time: "19:30",
    title: "Devolver o carro (até 21:00)",
    notes: "Depois, corrida de volta à hospedagem.",
    category: "logistica",
    placeName: "Foco Rent a Car Salvador",
    placeUrl: maps("Foco Rent a Car Salvador aeroporto"),
  },
  {
    dayKey: "2026-11-03",
    dayLabel: "03/nov",
    sort: 10,
    time: "manhã",
    title: "Praia de Stella Maris",
    notes: "Feriado: comércio fechado. Sem carro — usar app de corrida.",
    category: "passeio",
    placeName: "Praia de Stella Maris",
    placeUrl: maps("Praia de Stella Maris Salvador"),
  },
  {
    dayKey: "2026-11-03",
    dayLabel: "03/nov",
    sort: 20,
    time: "11:30",
    title: "Almoço no Midispache Vegan",
    notes: "Seg 11h–15h · Brotas. B-Vegan e Rango fechados na segunda.",
    category: "comida",
    placeName: "Midispache Vegan",
    placeUrl: maps("Midispache Vegan Brotas Salvador"),
  },
  {
    dayKey: "2026-11-03",
    dayLabel: "03/nov",
    sort: 30,
    time: "15:00",
    title: "Retorno e descanso na hospedagem",
    category: "passeio",
  },
  {
    dayKey: "2026-11-03",
    dayLabel: "03/nov",
    sort: 40,
    time: "20:00",
    title: "Jantar: cozinha ou delivery",
    notes: "Loja B-Vegan fecha na segunda — delivery pode funcionar.",
    category: "comida",
    placeName: "B-Vegan",
    placeUrl: maps("B-Vegan Salvador Barra"),
  },
  {
    dayKey: "2026-11-04",
    dayLabel: "04/nov",
    sort: 10,
    time: "09:00",
    title: "Corrida até a Barra",
    notes: "~35–45 min.",
    category: "logistica",
    placeName: "Porto da Barra, Salvador",
    placeUrl: maps("Porto da Barra Salvador"),
  },
  {
    dayKey: "2026-11-04",
    dayLabel: "04/nov",
    sort: 20,
    time: "10:00",
    title: "Porto da Barra e Farol",
    notes: "Pôr do sol opcional à tarde.",
    category: "passeio",
    placeName: "Farol da Barra",
    placeUrl: maps("Farol da Barra Salvador"),
  },
  {
    dayKey: "2026-11-04",
    dayLabel: "04/nov",
    sort: 30,
    time: "12:30",
    title: "Almoço no Ramma",
    notes: "Ter 11h30–15h · vegetariano.",
    category: "comida",
    placeName: "Ramma Salvador",
    placeUrl: maps("Ramma restaurante Barra Salvador"),
  },
  {
    dayKey: "2026-11-04",
    dayLabel: "04/nov",
    sort: 40,
    time: "15:00",
    title: "Bonfim e Mercado Modelo",
    category: "passeio",
    placeName: "Igreja do Bonfim",
    placeUrl: maps("Igreja do Senhor do Bonfim Salvador"),
  },
  {
    dayKey: "2026-11-04",
    dayLabel: "04/nov",
    sort: 45,
    title: "Mercado Modelo",
    category: "passeio",
    placeName: "Mercado Modelo Salvador",
    placeUrl: maps("Mercado Modelo Salvador"),
  },
  {
    dayKey: "2026-11-04",
    dayLabel: "04/nov",
    sort: 50,
    time: "18:00",
    title: "Jantar no B-Vegan",
    notes: "Ter 15h–21h30.",
    category: "comida",
    placeName: "B-Vegan",
    placeUrl: maps("B-Vegan Salvador Barra"),
  },
  {
    dayKey: "2026-11-04",
    dayLabel: "04/nov",
    sort: 60,
    time: "20:30",
    title: "Retorno a Stella Maris",
    category: "logistica",
    placeName: "Stella Maris, Salvador",
    placeUrl: maps("Stella Maris Salvador BA"),
  },
  {
    dayKey: "2026-11-05",
    dayLabel: "05/nov",
    sort: 10,
    time: "manhã",
    title: "Café e último banho em Stella Maris",
    category: "passeio",
    placeName: "Praia de Stella Maris",
    placeUrl: maps("Praia de Stella Maris Salvador"),
  },
  {
    dayKey: "2026-11-05",
    dayLabel: "05/nov",
    sort: 20,
    time: "11:45",
    title: "Check-out e corrida ao aeroporto",
    notes: "Check-out até 12h. SSA ~15–25 min. Margem para o voo 14h55.",
    category: "logistica",
    placeName: "Aeroporto Internacional de Salvador (SSA)",
    placeUrl: maps("Aeroporto Internacional de Salvador Deputado Luís Eduardo Magalhães SSA"),
  },
  {
    dayKey: "2026-11-05",
    dayLabel: "05/nov",
    sort: 30,
    time: "14:55",
    title: "Voo de volta",
    notes: "Direto · cerca de 1h50.",
    category: "logistica",
    placeName: "Aeroporto Internacional de Salvador (SSA)",
    placeUrl: maps("Aeroporto Internacional de Salvador Deputado Luís Eduardo Magalhães SSA"),
  },
];

export function salvadorSeedActions(): TripAction[] {
  return actions.map((action, index) => ({
    ...action,
    tripSlug: SALVADOR_TRIP.slug,
    done: false,
    custom: false,
    seedKey: `salvador-${action.dayKey}-${index}`,
  }));
}
